# Generated by Django 2.2.6 on 2019-11-06 02:52

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cebuMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objectid', models.IntegerField()),
                ('iso', models.CharField(max_length=254)),
                ('name_0', models.CharField(max_length=254)),
                ('name_1', models.CharField(max_length=254)),
                ('varname_1', models.CharField(max_length=254)),
                ('nl_name_1', models.CharField(max_length=254)),
                ('hasc_1', models.CharField(max_length=254)),
                ('fips_1', models.CharField(max_length=254)),
                ('cc_1', models.CharField(max_length=254)),
                ('type_1', models.CharField(max_length=254)),
                ('engtype_1', models.CharField(max_length=254)),
                ('validfr_1', models.CharField(max_length=254)),
                ('validto_1', models.CharField(max_length=254)),
                ('remarks_1', models.CharField(max_length=254)),
                ('name_2', models.CharField(max_length=254)),
                ('varname_2', models.CharField(max_length=254)),
                ('nl_name_2', models.CharField(max_length=254)),
                ('hasc_2', models.CharField(max_length=254)),
                ('fips_2', models.CharField(max_length=254)),
                ('cc_2', models.CharField(max_length=254)),
                ('type_2', models.CharField(max_length=254)),
                ('engtype_2', models.CharField(max_length=254)),
                ('validfr_2', models.CharField(max_length=254)),
                ('validto_2', models.CharField(max_length=254)),
                ('remarks_2', models.CharField(max_length=254)),
                ('name_3', models.CharField(max_length=254)),
                ('varname_3', models.CharField(max_length=254)),
                ('nl_name_3', models.CharField(max_length=254)),
                ('hasc_3', models.CharField(max_length=254)),
                ('type_3', models.CharField(max_length=254)),
                ('engtype_3', models.CharField(max_length=254)),
                ('validfr_3', models.CharField(max_length=254)),
                ('validto_3', models.CharField(max_length=254)),
                ('remarks_3', models.CharField(max_length=254)),
                ('name_4', models.CharField(max_length=254)),
                ('varname_4', models.CharField(max_length=254)),
                ('type_4', models.CharField(max_length=254)),
                ('engtype_4', models.CharField(max_length=254)),
                ('validfr_4', models.CharField(max_length=254)),
                ('validto_4', models.CharField(max_length=254)),
                ('remarks_4', models.CharField(max_length=254)),
                ('name_5', models.CharField(max_length=254)),
                ('type_5', models.CharField(max_length=254)),
                ('engtype_5', models.CharField(max_length=254)),
                ('validfr_5', models.CharField(max_length=254)),
                ('validto_5', models.CharField(max_length=254)),
                ('shape_leng', models.FloatField()),
                ('shape_area', models.FloatField()),
                ('bngy', models.CharField(max_length=30)),
                ('psgc_bgy', models.CharField(max_length=15)),
                ('geom', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Incidence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('address', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
            ],
        ),
    ]
