# Generated by Django 2.2.6 on 2019-11-06 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cebuMap',
            new_name='CebuBrgys',
        ),
    ]
