# Generated by Django 2.2.6 on 2019-11-06 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0004_cebumap_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cebumap',
            name='ceb_map',
            field=models.URLField(default='http://localhost:8000/cebuMap', max_length=250, null=True),
        ),
    ]
