# Generated by Django 2.2.6 on 2019-11-06 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0005_auto_20191106_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cebumap',
            name='location',
        ),
    ]
