# Generated by Django 2.2.6 on 2019-11-06 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0006_remove_cebumap_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cebumap',
            name='ceb_map',
            field=models.URLField(default='http://localhost:8000/cebuMap', editable=False, max_length=250, null=True),
        ),
    ]
