# Generated by Django 2.2.6 on 2019-11-06 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0009_auto_20191106_1806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cebumap',
            name='ceb_map',
            field=models.URLField(editable=False, max_length=250),
        ),
    ]
