# Generated by Django 2.2.6 on 2019-11-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0011_auto_20191106_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cebumap',
            name='ceb_map',
            field=models.URLField(max_length=250),
        ),
    ]
