# Generated by Django 2.2.6 on 2019-11-06 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0014_auto_20191106_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cebumap',
            name='ceb_map',
        ),
    ]
