# Generated by Django 2.2.6 on 2019-11-07 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0015_remove_cebumap_ceb_map'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cebubrgys',
            options={'verbose_name_plural': 'Cebu Brgys'},
        ),
        migrations.AlterModelOptions(
            name='cebumap',
            options={'verbose_name_plural': 'Cebu Map'},
        ),
    ]
