# Generated by Django 2.2.6 on 2019-11-22 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0016_auto_20191107_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cebubrgys',
            options={'verbose_name_plural': 'Cebu Barangays'},
        ),
    ]
