# Generated by Django 2.2.6 on 2019-11-22 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0018_cebubarangays'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CebuBrgys',
        ),
    ]
