# Generated by Django 2.2.6 on 2019-12-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0058_patientnotification_status'),
        ('cebuMap', '0019_delete_cebubrgys'),
    ]

    operations = [
        migrations.AddField(
            model_name='cebubarangays',
            name='hiv_pop',
            field=models.ManyToManyField(blank=True, related_name='brgy_hiv_pop', to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='cebubarangays',
            name='no_hiv',
            field=models.ManyToManyField(blank=True, related_name='brgy_stage_neg', to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='cebubarangays',
            name='stage_0',
            field=models.ManyToManyField(blank=True, related_name='brgy_stage_0', to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='cebubarangays',
            name='stage_1',
            field=models.ManyToManyField(blank=True, related_name='brgy_stage_1', to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='cebubarangays',
            name='stage_2',
            field=models.ManyToManyField(blank=True, related_name='brgy_stage_2', to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='cebubarangays',
            name='stage_3',
            field=models.ManyToManyField(blank=True, related_name='brgy_stage_3', to='patient.Patient'),
        ),
    ]
