# Generated by Django 2.2.6 on 2019-12-13 05:29

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0020_auto_20191213_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cebubarangays',
            name='bngy',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='cc_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='cc_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='engtype_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='engtype_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='engtype_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='engtype_4',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='engtype_5',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='fips_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='fips_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='geom',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='hasc_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='hasc_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='hasc_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='iso',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='name_0',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='name_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='name_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='name_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='name_4',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='name_5',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='nl_name_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='nl_name_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='nl_name_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='psgc_bgy',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='remarks_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='remarks_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='remarks_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='remarks_4',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='shape_area',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='shape_leng',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='type_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='type_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='type_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='type_4',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='type_5',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validfr_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validfr_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validfr_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validfr_4',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validfr_5',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validto_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validto_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validto_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validto_4',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='validto_5',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='varname_1',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='varname_2',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='varname_3',
            field=models.CharField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='varname_4',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
