# Generated by Django 2.2.6 on 2019-12-13 05:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cebuMap', '0021_auto_20191213_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cebubarangays',
            name='no_hiv',
        ),
        migrations.RemoveField(
            model_name='cebubarangays',
            name='stage_0',
        ),
        migrations.RemoveField(
            model_name='cebubarangays',
            name='stage_1',
        ),
        migrations.RemoveField(
            model_name='cebubarangays',
            name='stage_2',
        ),
        migrations.RemoveField(
            model_name='cebubarangays',
            name='stage_3',
        ),
    ]
