# Generated by Django 2.2.6 on 2020-01-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0073_auto_20200107_1215'),
        ('cebuMap', '0024_auto_20200107_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='cebubarangays',
            name='deceased',
            field=models.ManyToManyField(blank=True, related_name='brgy_deceased', to='patient.Patient'),
        ),
        migrations.AddField(
            model_name='cebubarangays',
            name='migrated',
            field=models.ManyToManyField(blank=True, related_name='brgy_migrated', to='patient.Patient'),
        ),
        migrations.AlterField(
            model_name='cebubarangays',
            name='for_screening',
            field=models.ManyToManyField(blank=True, related_name='brgy_screening', to='patient.Patient'),
        ),
    ]
