# Generated by Django 2.2.6 on 2019-11-04 07:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('text', models.TextField(blank=True, max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ICRForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastname', models.CharField(blank=True, default='None', max_length=100)),
                ('firstname', models.CharField(blank=True, default='secret', max_length=100)),
                ('middlename', models.CharField(default='None', max_length=100)),
                ('vDate', models.CharField(blank=True, default='None', max_length=100)),
                ('age', models.CharField(blank=True, default='0', max_length=3)),
                ('bDate', models.CharField(blank=True, default='None', max_length=100)),
                ('sex', models.CharField(blank=True, default='None', max_length=2)),
                ('cStatus', models.CharField(blank=True, default='None', max_length=2)),
                ('phoneNum', models.CharField(blank=True, default='0', max_length=3)),
                ('homeAdd', models.CharField(blank=True, default='Cebu City', max_length=100)),
                ('occ', models.CharField(blank=True, default='None', max_length=100)),
                ('workAdd', models.CharField(blank=True, default='None', max_length=100)),
                ('workNum', models.CharField(blank=True, default='123456789', max_length=3)),
                ('vPurpose', models.CharField(blank=True, default='None', max_length=2)),
                ('symptoms', models.CharField(blank=True, default='None', max_length=2)),
                ('specification', models.CharField(blank=True, default='None', max_length=100)),
                ('doc_remarks', models.ManyToManyField(to='patient.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='PatientNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=100)),
                ('subject', models.CharField(blank=True, default='None', max_length=100)),
                ('user_type', models.CharField(blank=True, default='None', max_length=15)),
                ('notif', models.CharField(blank=True, default='None', max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='ProfileForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(blank=True, default='None', max_length=100)),
                ('codeName', models.CharField(blank=True, default='None', max_length=100)),
                ('realName', models.CharField(blank=True, default='None', max_length=100)),
                ('mmName', models.CharField(blank=True, default='None', max_length=100)),
                ('addrs', models.CharField(blank=True, default='None', max_length=100)),
                ('province', models.CharField(blank=True, default='None', max_length=100)),
                ('age', models.CharField(blank=True, default='0', max_length=3)),
                ('sex', models.CharField(blank=True, default='None', max_length=100)),
                ('status', models.CharField(blank=True, default='None', max_length=100)),
                ('bdate', models.CharField(blank=True, default='None', max_length=100)),
                ('pdate', models.CharField(blank=True, default='None', max_length=100)),
                ('nation', models.CharField(blank=True, default='Filipino', max_length=100)),
                ('ed', models.CharField(blank=True, default='None', max_length=100)),
                ('occ', models.CharField(blank=True, default='None', max_length=100)),
                ('contact', models.CharField(blank=True, default='None', max_length=100)),
                ('philNum', models.CharField(blank=True, default='None', max_length=100)),
                ('doc_remarks', models.ManyToManyField(to='patient.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('doc_remarks', models.CharField(blank=True, default='None', max_length=500)),
                ('comment', models.ManyToManyField(to='patient.Comment')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='PendingDoctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pdoctor', models.ManyToManyField(to='doctor.Doctor')),
            ],
        ),
        migrations.CreateModel(
            name='MedHistForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=100)),
                ('exposure', models.CharField(blank=True, default='negative', max_length=100)),
                ('other_conditions', models.CharField(blank=True, default='none', max_length=100)),
                ('date_diagnosed', models.CharField(blank=True, default='None', max_length=100)),
                ('doc_remarks', models.ManyToManyField(to='patient.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('firstname', models.CharField(blank=True, default='none', max_length=100)),
                ('lastname', models.CharField(blank=True, default='none', max_length=100)),
                ('username', models.CharField(blank=True, default='none', max_length=100)),
                ('birthdate', models.DateField(blank=True, default=datetime.date.today)),
                ('age', models.IntegerField(blank=True, default=5)),
                ('presentAddress', models.CharField(blank=True, default='none', max_length=100)),
                ('work', models.CharField(blank=True, default='none', max_length=100)),
                ('workAddress', models.CharField(blank=True, default='none', max_length=100)),
                ('callNumber', models.CharField(blank=True, default='0', max_length=100)),
                ('email', models.CharField(blank=True, default='none', max_length=100)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('hivStatus', models.CharField(blank=True, default='negative', max_length=100)),
                ('icr', models.OneToOneField(on_delete='models.CASCADE', primary_key=True, serialize=False, to='patient.ICRForm')),
                ('approvedScheds', models.ManyToManyField(related_name='patient_approved_sched', to='doctor.DoctorSchedule')),
                ('finishedScheds', models.ManyToManyField(related_name='patient_finished_scheds', to='doctor.DoctorSchedule')),
                ('medhist', models.OneToOneField(null=True, on_delete='models.CASCADE', to='patient.MedHistForm')),
                ('myDoctors', models.ManyToManyField(to='doctor.Doctor')),
                ('patientNotif', models.ManyToManyField(to='patient.PatientNotification')),
                ('pendingDoctors', models.ManyToManyField(to='doctor.DoctorNotification')),
                ('pendingScheds', models.ManyToManyField(related_name='patient_pending_sched', to='doctor.DoctorSchedule')),
                ('personalRecord', models.ManyToManyField(to='patient.PersonalRecord')),
                ('profile', models.OneToOneField(null=True, on_delete='models.CASCADE', to='patient.ProfileForm')),
                ('rejectedScheds', models.ManyToManyField(related_name='patient_rejected_scheds', to='doctor.DoctorSchedule')),
            ],
        ),
    ]
