# Generated by Django 2.2.6 on 2019-11-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20191104_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='approvedScheds',
            field=models.ManyToManyField(blank=True, related_name='patient_approved_sched', to='doctor.DoctorSchedule'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='finishedScheds',
            field=models.ManyToManyField(blank=True, related_name='patient_finished_scheds', to='doctor.DoctorSchedule'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='icr',
            field=models.OneToOneField(blank=True, on_delete='models.CASCADE', primary_key=True, serialize=False, to='patient.ICRForm'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medhist',
            field=models.OneToOneField(blank=True, null=True, on_delete='models.CASCADE', to='patient.MedHistForm'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='myDoctors',
            field=models.ManyToManyField(blank=True, to='doctor.Doctor'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patientNotif',
            field=models.ManyToManyField(blank=True, to='patient.PatientNotification'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pendingDoctors',
            field=models.ManyToManyField(blank=True, to='doctor.DoctorNotification'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='pendingScheds',
            field=models.ManyToManyField(blank=True, related_name='patient_pending_sched', to='doctor.DoctorSchedule'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='personalRecord',
            field=models.ManyToManyField(blank=True, to='patient.PersonalRecord'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete='models.CASCADE', to='patient.ProfileForm'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='rejectedScheds',
            field=models.ManyToManyField(blank=True, related_name='patient_rejected_scheds', to='doctor.DoctorSchedule'),
        ),
    ]
