# Generated by Django 2.2.6 on 2019-11-04 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_auto_20191104_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icrform',
            name='age',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='icrform',
            name='cStatus',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='icrform',
            name='phoneNum',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='icrform',
            name='sex',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='icrform',
            name='symptoms',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='icrform',
            name='vPurpose',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='icrform',
            name='workNum',
            field=models.CharField(blank=True, default='123456789', max_length=100),
        ),
    ]
