# Generated by Django 2.2.6 on 2019-11-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20191104_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='password',
            field=models.CharField(default='none', max_length=100, null=True),
        ),
    ]
