# Generated by Django 2.2.7 on 2019-11-05 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0005_auto_20191104_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientLocationDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(blank=True, max_length=200)),
                ('lon', models.CharField(blank=True, max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('patientName', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
