# Generated by Django 2.2.7 on 2019-11-05 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_patientlocationdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='locationDetails',
            field=models.ManyToManyField(blank=True, to='patient.PatientLocationDetails'),
        ),
    ]
