# Generated by Django 2.2.7 on 2019-11-05 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_patient_locationdetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='locationDetails',
        ),
        migrations.AddField(
            model_name='patient',
            name='locationDetails',
            field=models.OneToOneField(blank=True, null=True, on_delete='models.CASCADE', to='patient.PatientLocationDetails'),
        ),
    ]
