# Generated by Django 2.2.6 on 2019-11-08 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_auto_20191105_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icrform',
            name='doc_remarks',
            field=models.ManyToManyField(blank=True, to='doctor.Note'),
        ),
        migrations.AlterField(
            model_name='medhistform',
            name='doc_remarks',
            field=models.ManyToManyField(blank=True, to='doctor.Note'),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='comment',
            field=models.ManyToManyField(blank=True, to='doctor.Note'),
        ),
        migrations.AlterField(
            model_name='profileform',
            name='doc_remarks',
            field=models.ManyToManyField(blank=True, to='doctor.Note'),
        ),
    ]
