# Generated by Django 2.2.6 on 2019-11-08 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0009_auto_20191108_1032'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
