# Generated by Django 2.2.6 on 2019-11-08 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icrform',
            old_name='vPurpose',
            new_name='purpose_of_visit',
        ),
    ]
