# Generated by Django 2.2.6 on 2019-11-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_auto_20191108_1533'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icrform',
            old_name='lastname',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='lastname',
            new_name='last_name',
        ),
    ]
