# Generated by Django 2.2.6 on 2019-11-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_auto_20191108_1540'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icrform',
            old_name='firstname',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='firstname',
            new_name='first_name',
        ),
    ]
