# Generated by Django 2.2.6 on 2019-11-08 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0013_auto_20191108_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='presentAddress',
            new_name='present_address',
        ),
    ]
