# Generated by Django 2.2.6 on 2019-11-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_auto_20191108_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='workAddress',
            new_name='work_address',
        ),
    ]
