# Generated by Django 2.2.6 on 2019-11-08 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0015_auto_20191108_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='callNumber',
            new_name='call_number',
        ),
    ]
