# Generated by Django 2.2.6 on 2019-11-08 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0016_auto_20191108_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='hivStatus',
            new_name='HIV_Status',
        ),
    ]
