# Generated by Django 2.2.6 on 2019-11-08 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0019_auto_20191108_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='myDoctors',
            new_name='my_doctors',
        ),
    ]
