# Generated by Django 2.2.6 on 2019-11-08 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0020_auto_20191108_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='approvedScheds',
            new_name='approved_schedules',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='finishedScheds',
            new_name='finished_schedules',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patientNotif',
            new_name='patient_notifications',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pendingDoctors',
            new_name='pending_doctors',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='pendingScheds',
            new_name='pending_schedules',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='personalRecord',
            new_name='personal_records',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='rejectedScheds',
            new_name='rejected_schedules',
        ),
    ]
