# Generated by Django 2.2.6 on 2019-11-08 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0021_auto_20191108_1625'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icrform',
            old_name='bDate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='icrform',
            old_name='cStatus',
            new_name='civil_status',
        ),
        migrations.RenameField(
            model_name='icrform',
            old_name='homeAdd',
            new_name='home_address',
        ),
        migrations.RenameField(
            model_name='icrform',
            old_name='occ',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='icrform',
            old_name='phoneNum',
            new_name='phone_number',
        ),
        migrations.RenameField(
            model_name='profileform',
            old_name='addrs',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='profileform',
            old_name='bdate',
            new_name='birthdate',
        ),
        migrations.RenameField(
            model_name='profileform',
            old_name='codeName',
            new_name='code_name',
        ),
        migrations.RenameField(
            model_name='profileform',
            old_name='mmName',
            new_name='mother_maiden_name',
        ),
        migrations.RenameField(
            model_name='profileform',
            old_name='occ',
            new_name='occupation',
        ),
        migrations.RenameField(
            model_name='profileform',
            old_name='realName',
            new_name='real_name',
        ),
    ]
