# Generated by Django 2.2.6 on 2019-11-08 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0022_auto_20191108_1649'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icrform',
            old_name='vDate',
            new_name='date_of_visit',
        ),
        migrations.RenameField(
            model_name='icrform',
            old_name='middlename',
            new_name='middle_name',
        ),
        migrations.RenameField(
            model_name='icrform',
            old_name='workAdd',
            new_name='work_address',
        ),
        migrations.RenameField(
            model_name='icrform',
            old_name='workNum',
            new_name='work_number',
        ),
        migrations.RenameField(
            model_name='patientlocationdetails',
            old_name='patientName',
            new_name='patient_name',
        ),
        migrations.RenameField(
            model_name='patientnotification',
            old_name='notif',
            new_name='notification',
        ),
    ]
