# Generated by Django 2.2.6 on 2019-11-08 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0023_auto_20191108_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='icrform',
            old_name='doc_remarks',
            new_name='doctor_remarks',
        ),
        migrations.RenameField(
            model_name='medhistform',
            old_name='doc_remarks',
            new_name='doctor_remarks',
        ),
        migrations.RenameField(
            model_name='personalrecord',
            old_name='doc_remarks',
            new_name='doctor_remarks',
        ),
        migrations.RenameField(
            model_name='profileform',
            old_name='doc_remarks',
            new_name='doctor_remarks',
        ),
    ]
