# Generated by Django 2.2.6 on 2019-11-08 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0024_auto_20191108_1707'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='icrform',
            options={'verbose_name_plural': 'ICR Forms'},
        ),
        migrations.AlterModelOptions(
            name='medhistform',
            options={'verbose_name_plural': 'Medical History Forms'},
        ),
        migrations.AlterModelOptions(
            name='patientlocationdetails',
            options={'verbose_name_plural': 'Patient Location Details'},
        ),
        migrations.AlterModelOptions(
            name='patientnotification',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Patient Notifications'},
        ),
        migrations.AlterModelOptions(
            name='pendingdoctor',
            options={'verbose_name_plural': 'Pending Doctors'},
        ),
        migrations.AlterModelOptions(
            name='personalrecord',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Personal Records'},
        ),
        migrations.AlterModelOptions(
            name='profileform',
            options={'verbose_name_plural': 'Profile Forms'},
        ),
        migrations.RenameField(
            model_name='patientnotification',
            old_name='name',
            new_name='doctor_name',
        ),
        migrations.AddField(
            model_name='patientnotification',
            name='patient_name',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
