# Generated by Django 2.2.6 on 2019-11-10 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0027_auto_20191110_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_log_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 10, 6, 42, 342109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_log_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 10, 6, 42, 342109, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientnotification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 323102, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pendingdoctor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 324505, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 319101, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 319101, tzinfo=utc)),
        ),
    ]
