# Generated by Django 2.2.6 on 2019-11-10 15:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0030_auto_20191110_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='last_log_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 15, 32, 58, 419230, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_log_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 10, 15, 32, 58, 419230, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='patientnotification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 15, 32, 58, 411233, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='pendingdoctor',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 15, 32, 58, 412229, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 15, 32, 58, 410231, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 15, 32, 58, 410231, tzinfo=utc)),
        ),
    ]
