# Generated by Django 2.2.6 on 2019-11-10 16:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0037_auto_20191110_2356'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='login_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_log_in',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='patient',
            name='last_log_out',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
