# Generated by Django 2.2.6 on 2019-11-10 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0039_auto_20191111_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icrform',
            name='middle_name',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
