# Generated by Django 2.2.6 on 2019-11-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0040_auto_20191111_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='new_patient_notifications',
            field=models.ManyToManyField(blank=True, related_name='new_patient_notifications', to='patient.PatientNotification'),
        ),
    ]
