# Generated by Django 2.2.6 on 2019-11-10 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0041_patient_new_patient_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='new_patient_notifications',
            new_name='patient_new_notifications',
        ),
    ]
