# Generated by Django 2.2.6 on 2019-11-11 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0042_auto_20191111_0157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientnotification',
            old_name='patient_name',
            new_name='patient_username',
        ),
    ]
