# Generated by Django 2.2.6 on 2019-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0044_auto_20191111_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientnotification',
            name='notification',
            field=models.CharField(blank=True, default='None', max_length=2000),
        ),
        migrations.AlterField(
            model_name='personalrecord',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
