# Generated by Django 2.2.6 on 2019-11-18 03:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0047_auto_20191112_0049'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientlocationdetails',
            options={'verbose_name_plural': 'Present Address Informations'},
        ),
    ]
