# Generated by Django 2.2.6 on 2019-11-18 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0048_auto_20191118_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnotification',
            name='action_type',
            field=models.CharField(blank=True, default='None', max_length=15),
        ),
    ]
