# Generated by Django 2.2.6 on 2019-11-18 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0049_patientnotification_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnotification',
            name='action_pk',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
