# Generated by Django 2.2.6 on 2019-11-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0033_auto_20191120_0116'),
        ('patient', '0050_patientnotification_action_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalrecord',
            name='doctor_remarks',
        ),
        migrations.AddField(
            model_name='icrform',
            name='docs_viewed',
            field=models.ManyToManyField(blank=True, to='doctor.UsersViewed'),
        ),
        migrations.AddField(
            model_name='medhistform',
            name='docs_viewed',
            field=models.ManyToManyField(blank=True, to='doctor.UsersViewed'),
        ),
        migrations.AddField(
            model_name='personalrecord',
            name='docs_viewed',
            field=models.ManyToManyField(blank=True, to='doctor.UsersViewed'),
        ),
        migrations.AddField(
            model_name='profileform',
            name='docs_viewed',
            field=models.ManyToManyField(blank=True, to='doctor.UsersViewed'),
        ),
        migrations.DeleteModel(
            name='PendingDoctor',
        ),
    ]
