# Generated by Django 2.2.6 on 2019-11-29 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0052_patientlocationdetails_hiv_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='HIV_Status',
            new_name='HIV_status',
        ),
    ]
