# Generated by Django 2.2.6 on 2019-12-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0054_patient_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientlocationdetails',
            name='hiv_level',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientlocationdetails',
            name='lat',
            field=models.CharField(blank=True, default='10.3157', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientlocationdetails',
            name='location',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientlocationdetails',
            name='lon',
            field=models.CharField(blank=True, default='123.8854', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientlocationdetails',
            name='patient_name',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientlocationdetails',
            name='username',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='patientlocationdetails',
            name='work',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
