# Generated by Django 2.2.6 on 2019-12-04 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0057_patient_tel_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientnotification',
            name='status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
