# Generated by Django 2.2.6 on 2019-12-15 16:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0058_patientnotification_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='medhistform',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='medhistform',
            name='parent_pk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='medhistform',
            name='username',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.RemoveField(
            model_name='patient',
            name='medical_history',
        ),
        migrations.AddField(
            model_name='patient',
            name='medical_history',
            field=models.ManyToManyField(blank=True, to='patient.MedHistForm'),
        ),
    ]
