# Generated by Django 2.2.6 on 2019-12-16 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0062_auto_20191216_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='meds',
            field=models.ManyToManyField(blank=True, to='patient.Medication'),
        ),
    ]
