# Generated by Django 2.2.6 on 2019-12-16 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0063_patient_meds'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='parent_pk',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
