# Generated by Django 2.2.6 on 2019-12-18 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0065_auto_20191218_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='parent_pk',
            new_name='patient_pk',
        ),
    ]
