# Generated by Django 2.2.6 on 2019-12-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0067_auto_20191218_2005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='frequency',
        ),
        migrations.RemoveField(
            model_name='medication',
            name='time_interval',
        ),
        migrations.AddField(
            model_name='medication',
            name='doc_notes',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
