# Generated by Django 2.2.6 on 2019-12-19 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0068_auto_20191218_2006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientnotification',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name_plural': 'Notifications'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='location_details',
        ),
        migrations.AddField(
            model_name='patient',
            name='location_details',
            field=models.ManyToManyField(blank=True, to='patient.PatientLocationDetails'),
        ),
    ]
