# Generated by Django 2.2.6 on 2019-12-19 07:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0069_auto_20191219_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientlocationdetails',
            options={'get_latest_by': 'created_on', 'verbose_name_plural': 'Present Address Informations'},
        ),
        migrations.AlterModelOptions(
            name='patientnotification',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Notifications'},
        ),
        migrations.AddField(
            model_name='patientlocationdetails',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
