# Generated by Django 2.2.6 on 2019-12-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0070_auto_20191219_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='status',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
