# Generated by Django 2.2.6 on 2020-01-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0072_patientlocationdetails_patient_pk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientlocationdetails',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name_plural': 'Present Address Informations'},
        ),
    ]
