# Generated by Django 2.2.6 on 2020-01-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0074_auto_20200108_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientlocationdetails',
            name='status',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
