# Generated by Django 2.2.6 on 2020-01-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0075_patientlocationdetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='doc_notes',
            field=models.TextField(blank=True, default='none'),
        ),
    ]
