# Generated by Django 2.2.6 on 2020-01-23 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0077_patientlocationdetails_gen_loc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientlocationdetails',
            old_name='gen_loc',
            new_name='general_location',
        ),
    ]
