# Generated by Django 2.2.6 on 2020-01-24 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0078_auto_20200123_2207'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='slug',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
