# Generated by Django 2.2.6 on 2020-01-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0079_patient_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medication',
            old_name='intake_per_bottle',
            new_name='content_per_bottle',
        ),
        migrations.AddField(
            model_name='medication',
            name='drug_group',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='medication',
            name='medicine_type',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
    ]
