# Generated by Django 2.2.6 on 2020-01-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0080_auto_20200124_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='content_per_bottle',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
