# Generated by Django 2.2.6 on 2020-01-27 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0082_auto_20200127_1140'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('patient_name', models.CharField(blank=True, default='None', max_length=100)),
                ('patient_pk', models.IntegerField(blank=True, default=0)),
                ('year', models.CharField(blank=True, default='2019', max_length=10)),
                ('january', models.IntegerField(blank=True, default=0)),
                ('february', models.IntegerField(blank=True, default=0)),
                ('march', models.IntegerField(blank=True, default=0)),
                ('april', models.IntegerField(blank=True, default=0)),
                ('may', models.IntegerField(blank=True, default=0)),
                ('june', models.IntegerField(blank=True, default=0)),
                ('july', models.IntegerField(blank=True, default=0)),
                ('august', models.IntegerField(blank=True, default=0)),
                ('september', models.IntegerField(blank=True, default=0)),
                ('october', models.IntegerField(blank=True, default=0)),
                ('november', models.IntegerField(blank=True, default=0)),
                ('december', models.IntegerField(blank=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Monthly Statistics',
                'ordering': ['-created_on'],
                'get_latest_by': 'created_on',
            },
        ),
    ]
