# Generated by Django 2.2.6 on 2020-01-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0084_auto_20200127_1525'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientsmonthlystatistics',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name_plural': 'Patients Monthly Statistics'},
        ),
        migrations.AddField(
            model_name='patientsmonthlystatistics',
            name='patient_username',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
