# Generated by Django 2.2.6 on 2020-01-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0088_patientnotification_notif_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
