# Generated by Django 2.2.6 on 2020-02-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0089_patient_patient_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, upload_to='profile_pictures/media/'),
        ),
    ]
