# Generated by Django 2.2.6 on 2020-02-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0091_auto_20200201_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, upload_to='profile-pictures'),
        ),
    ]
