# Generated by Django 2.2.7 on 2020-02-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0077_auto_20200201_1510'),
        ('patient', '0093_remove_medhistform_doctor_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='medhistform',
            name='doctor_remarks',
            field=models.ManyToManyField(blank=True, to='doctor.Remark'),
        ),
    ]
