# Generated by Django 2.2.7 on 2020-02-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0094_medhistform_doctor_remarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icrform',
            name='doctor_remarks',
        ),
    ]
