# Generated by Django 2.2.7 on 2020-02-11 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0077_auto_20200201_1510'),
        ('patient', '0095_remove_icrform_doctor_remarks'),
    ]

    operations = [
        migrations.AddField(
            model_name='icrform',
            name='doctor_remarks',
            field=models.ManyToManyField(blank=True, to='doctor.Remark'),
        ),
    ]
