# Generated by Django 2.2.7 on 2020-02-12 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0096_icrform_doctor_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalrecord',
            name='comment',
            field=models.ManyToManyField(blank=True, null=True, to='doctor.Remark'),
        ),
    ]
