# Generated by Django 2.2.7 on 2020-02-12 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0097_auto_20200212_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalrecord',
            name='comment',
            field=models.ManyToManyField(blank=True, to='doctor.Remark'),
        ),
    ]
