# Generated by Django 2.2.7 on 2020-02-12 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0098_auto_20200212_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personalrecord',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='personalrecord',
            name='docs_viewed',
        ),
    ]
