# Generated by Django 2.2.7 on 2020-02-12 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0077_auto_20200201_1510'),
        ('patient', '0100_personalrecord_docs_viewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalrecord',
            name='comment',
            field=models.ManyToManyField(blank=True, to='doctor.Remark'),
        ),
    ]
