# Generated by Django 2.2.7 on 2020-04-01 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0101_personalrecord_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='profile',
        ),
    ]
