# Generated by Django 2.2.7 on 2020-04-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0102_remove_patient_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile',
            field=models.OneToOneField(blank=True, null=True, on_delete='models.CASCADE', to='patient.ProfileForm'),
        ),
    ]
