# Generated by Django 2.2.7 on 2020-02-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='backup_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Back Up Data', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Backup Data',
            },
        ),
        migrations.CreateModel(
            name='restore_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Restore Data', max_length=100, null=True)),
            ],
            options={
                'verbose_name_plural': 'Restore Data',
            },
        ),
    ]
