# Generated by Django 2.2.7 on 2020-02-18 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backup_and_restore', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='backup_data',
            new_name='Backup',
        ),
        migrations.RenameModel(
            old_name='restore_data',
            new_name='Restore',
        ),
    ]
