# Generated by Django 2.2.6 on 2019-11-04 07:43

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='None', max_length=100)),
                ('subject', models.CharField(blank=True, default='None', max_length=100)),
                ('user_type', models.CharField(blank=True, default='None', max_length=15)),
                ('notif', models.CharField(blank=True, default='None', max_length=100)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='DoctorStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.IntegerField(default=0)),
                ('last_updated', models.DateField(default=django.utils.timezone.now)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('week_count', models.IntegerField(default=0)),
                ('doctor_name', models.CharField(blank=True, default='None', max_length=100)),
                ('neg_patients', models.IntegerField(default=0)),
                ('stage_1', models.IntegerField(default=0)),
                ('stage_2', models.IntegerField(default=0)),
                ('stage_3', models.IntegerField(default=0)),
                ('all_patients_count', models.IntegerField(default=0)),
                ('my_patients_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_comment', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_username', models.CharField(blank=True, default='None', max_length=100)),
                ('patient_hiv_status', models.CharField(blank=True, default='None', max_length=100)),
                ('schedule_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('schedule_topic', models.CharField(blank=True, default='None', max_length=200)),
                ('schedule_notes', models.CharField(blank=True, default='None', max_length=500)),
                ('doc_incharge', models.CharField(blank=True, default='None', max_length=100)),
                ('status', models.CharField(blank=True, default='None', max_length=20)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('doc_remark', models.ManyToManyField(to='doctor.Note')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=200)),
                ('birthdate', models.DateField(blank=True, default=datetime.date.today)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('hospital_name', models.CharField(blank=True, max_length=100)),
                ('hospital_address', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=100)),
                ('doctorNotifs', models.ManyToManyField(to='doctor.DoctorNotification')),
                ('finished_scheds', models.ManyToManyField(related_name='doc_finished_scheds', to='doctor.DoctorSchedule')),
                ('pending_scheds', models.ManyToManyField(related_name='doc_pending_scheds', to='doctor.DoctorSchedule')),
                ('rejected_scheds', models.ManyToManyField(related_name='doc_rejected_scheds', to='doctor.DoctorSchedule')),
                ('schedules', models.ManyToManyField(to='doctor.DoctorSchedule')),
                ('weekly_stats', models.OneToOneField(null=True, on_delete='models.CASCADE', to='doctor.DoctorStats')),
            ],
        ),
    ]
