# Generated by Django 2.2.6 on 2019-11-08 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_auto_20191108_1437'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctorstats',
            options={'verbose_name_plural': 'Patients Statistics'},
        ),
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='doc_incharge',
            new_name='doc_in_charge',
        ),
    ]
