# Generated by Django 2.2.6 on 2019-11-08 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0003_auto_20191108_1506'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctornotification',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Doctor Notifications'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['-created_on'], 'verbose_name_plural': 'Doctor Schedules'},
        ),
        migrations.AddField(
            model_name='doctornotification',
            name='patient_username',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
