# Generated by Django 2.2.6 on 2019-11-10 10:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0004_auto_20191108_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotification',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 305154, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 301095, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='schedule_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 300094, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctorstats',
            name='last_updated',
            field=models.DateField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 298108, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='doctorstats',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 299107, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 10, 10, 6, 42, 297216, tzinfo=utc)),
        ),
    ]
