# Generated by Django 2.2.6 on 2019-11-10 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0016_auto_20191111_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='last_log_in',
            field=models.DateTimeField(verbose_name=datetime.datetime(2019, 11, 11, 0, 4, 31, 929966)),
        ),
    ]
