# Generated by Django 2.2.6 on 2019-11-10 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0022_doctorschedule_new_notif_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='new_notifs',
            field=models.ManyToManyField(related_name='new_doc_notifs', to='doctor.DoctorNotification'),
        ),
    ]
