# Generated by Django 2.2.6 on 2019-11-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0023_doctor_new_notifs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctorNotifs',
            field=models.ManyToManyField(blank=True, to='doctor.DoctorNotification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='finished_scheds',
            field=models.ManyToManyField(blank=True, related_name='doc_finished_scheds', to='doctor.DoctorSchedule'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='new_notifs',
            field=models.ManyToManyField(blank=True, related_name='new_doc_notifs', to='doctor.DoctorNotification'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='pending_scheds',
            field=models.ManyToManyField(blank=True, related_name='doc_pending_scheds', to='doctor.DoctorSchedule'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='rejected_scheds',
            field=models.ManyToManyField(blank=True, related_name='doc_rejected_scheds', to='doctor.DoctorSchedule'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='schedules',
            field=models.ManyToManyField(blank=True, to='doctor.DoctorSchedule'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='weekly_stats',
            field=models.OneToOneField(blank=True, null=True, on_delete='models.CASCADE', to='doctor.DoctorStats'),
        ),
    ]
