# Generated by Django 2.2.6 on 2019-11-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0024_auto_20191111_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotification',
            name='notif',
            field=models.CharField(blank=True, default='None', max_length=2000),
        ),
    ]
