# Generated by Django 2.2.6 on 2019-11-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0025_auto_20191111_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorschedule',
            name='schedule_notes',
            field=models.TextField(blank=True, default='None'),
        ),
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.TextField(blank=True, default='None'),
        ),
    ]
