# Generated by Django 2.2.6 on 2019-11-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0028_auto_20191112_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornotification',
            name='action_pk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='doctornotification',
            name='action_type',
            field=models.CharField(blank=True, default='None', max_length=15),
        ),
    ]
