# Generated by Django 2.2.6 on 2019-11-18 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0029_auto_20191118_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctornotification',
            name='action_type',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
