# Generated by Django 2.2.6 on 2019-11-18 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0030_auto_20191118_2251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctornotification',
            old_name='notification_type',
            new_name='subject',
        ),
    ]
