# Generated by Django 2.2.6 on 2019-11-19 03:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0031_auto_20191118_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remark',
            name='seen_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
