# Generated by Django 2.2.6 on 2019-11-19 17:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0032_auto_20191119_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersViewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seen_flag', models.BooleanField(blank=True, default=False)),
                ('seen_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('viewer_type', models.CharField(blank=True, max_length=100)),
                ('viewed_type', models.CharField(blank=True, max_length=100)),
                ('viewer_name', models.CharField(blank=True, max_length=100)),
                ('viewed_pk', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='remark',
            name='seen',
        ),
        migrations.RemoveField(
            model_name='remark',
            name='seen_date',
        ),
        migrations.AddField(
            model_name='remark',
            name='doc_views_details',
            field=models.ManyToManyField(blank=True, to='doctor.UsersViewed'),
        ),
    ]
