# Generated by Django 2.2.6 on 2019-11-19 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0034_usersviewed_file_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersviewed',
            options={'verbose_name_plural': 'Users Viewed'},
        ),
        migrations.AddField(
            model_name='doctorschedule',
            name='doc_views_details',
            field=models.ManyToManyField(blank=True, to='doctor.UsersViewed'),
        ),
    ]
