# Generated by Django 2.2.6 on 2019-11-20 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0035_auto_20191120_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='remark_parent_type',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
