# Generated by Django 2.2.6 on 2019-11-20 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0037_auto_20191120_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='remark',
            name='remark_parent_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='remark',
            name='remark_receiver',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
