# Generated by Django 2.2.6 on 2019-11-25 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0039_remark_seen_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorschedule',
            old_name='doc_views_details',
            new_name='users_viewed',
        ),
    ]
