# Generated by Django 2.2.6 on 2019-11-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0040_auto_20191125_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorschedule',
            name='action_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
