# Generated by Django 2.2.6 on 2019-11-29 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0041_doctorschedule_action_taken'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornotification',
            name='action_taken',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='doctorschedule',
            name='doc_remark',
            field=models.ManyToManyField(blank=True, to='doctor.Remark'),
        ),
    ]
