# Generated by Django 2.2.6 on 2019-12-03 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0042_auto_20191129_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='email',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_address',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='hospital_name',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='password',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(blank=True, default='none', max_length=200),
        ),
        migrations.AlterField(
            model_name='remark',
            name='author',
            field=models.CharField(blank=True, default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='remark',
            name='remark_parent_type',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='remark',
            name='remark_receiver',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersviewed',
            name='file_owner',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersviewed',
            name='viewed_type',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersviewed',
            name='viewer_name',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='usersviewed',
            name='viewer_type',
            field=models.CharField(blank=True, default='None', max_length=100),
        ),
    ]
