# Generated by Django 2.2.6 on 2019-12-16 05:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0043_auto_20191203_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('drug_name', models.CharField(blank=True, default='none', max_length=200)),
                ('unit_of_measure', models.CharField(blank=True, default='none', max_length=200)),
                ('intake_per_bottle', models.CharField(blank=True, default='none', max_length=200)),
                ('availability', models.BooleanField(blank=True, default=False)),
                ('stocks_on_hand', models.IntegerField(blank=True, default=0)),
            ],
        ),
    ]
