# Generated by Django 2.2.6 on 2019-12-19 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0044_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorstats',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
