# Generated by Django 2.2.6 on 2019-12-19 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0045_doctorstats_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='weekly_stats',
            new_name='p_handled_stats',
        ),
    ]
