# Generated by Django 2.2.6 on 2019-12-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0046_auto_20191219_2149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorstats',
            name='updated_on',
        ),
    ]
