# Generated by Django 2.2.6 on 2019-12-19 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0047_remove_doctorstats_updated_on'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorstats',
            old_name='my_patients_count',
            new_name='doc_patients_count',
        ),
    ]
