# Generated by Django 2.2.6 on 2019-12-19 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0048_auto_20191219_2250'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, default='2019', max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='doctorstats',
            name='monthly_stats',
            field=models.ManyToManyField(blank=True, to='doctor.MonthlyStatistics'),
        ),
    ]
