# Generated by Django 2.2.6 on 2019-12-20 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0049_auto_20191219_2302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorstats',
            name='monthly_stats',
        ),
        migrations.DeleteModel(
            name='MonthlyStatistics',
        ),
    ]
