# Generated by Django 2.2.6 on 2019-12-20 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0050_auto_20191220_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(blank=True, default='2019', max_length=10)),
                ('january', models.IntegerField(blank=True, default=0)),
                ('february', models.IntegerField(blank=True, default=0)),
                ('march', models.IntegerField(blank=True, default=0)),
                ('april', models.IntegerField(blank=True, default=0)),
                ('may', models.IntegerField(blank=True, default=0)),
                ('june', models.IntegerField(blank=True, default=0)),
                ('july', models.IntegerField(blank=True, default=0)),
                ('august', models.IntegerField(blank=True, default=0)),
                ('september', models.IntegerField(blank=True, default=0)),
                ('october', models.IntegerField(blank=True, default=0)),
                ('november', models.IntegerField(blank=True, default=0)),
                ('december', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='doctorstats',
            name='monthly_stats',
            field=models.ManyToManyField(blank=True, to='doctor.MonthlyStatistics'),
        ),
    ]
