# Generated by Django 2.2.6 on 2019-12-20 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0051_auto_20191221_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlystatistics',
            name='doc_pk',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='monthlystatistics',
            name='doctor_name',
            field=models.CharField(blank=True, default='None', max_length=10),
        ),
    ]
