# Generated by Django 2.2.6 on 2019-12-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0054_auto_20191221_0215'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlystatistics',
            options={'verbose_name_plural': 'Monthly Statistics'},
        ),
        migrations.AddField(
            model_name='monthlystatistics',
            name='patient_pk',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
