# Generated by Django 2.2.6 on 2019-12-20 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0055_auto_20191221_0316'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlystatistics',
            options={'get_latest_by': 'created_on', 'verbose_name_plural': 'Monthly Statistics'},
        ),
        migrations.RenameField(
            model_name='monthlystatistics',
            old_name='created_date',
            new_name='created_on',
        ),
    ]
