# Generated by Django 2.2.6 on 2020-01-17 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0061_auto_20200117_1642'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='doctorstats',
            options={'verbose_name_plural': 'Patients Statistics'},
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='doctorstats',
            name='created_on',
        ),
    ]
