# Generated by Django 2.2.6 on 2020-01-21 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0064_auto_20200117_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlystatistics',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name_plural': 'Monthly Statistics'},
        ),
    ]
