# Generated by Django 2.2.6 on 2020-01-24 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0066_auto_20200123_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlystatistics',
            options={'get_latest_by': 'created_on', 'ordering': ['-created_on'], 'verbose_name_plural': 'Monthly Statistics'},
        ),
    ]
