# Generated by Django 2.2.6 on 2020-01-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0067_auto_20200124_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='intake_per_bottle',
            new_name='content_per_bottle',
        ),
        migrations.AddField(
            model_name='medicine',
            name='drug_group',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='medicine_type',
            field=models.CharField(blank=True, default='none', max_length=200),
        ),
        migrations.AddField(
            model_name='medicine',
            name='patients_on_medication',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
