# Generated by Django 2.2.6 on 2020-01-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0069_auto_20200124_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='field_specialty',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='phone_number',
            field=models.CharField(blank=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='position',
            field=models.CharField(blank=True, default='none', max_length=100),
        ),
    ]
