# Generated by Django 2.2.6 on 2020-01-27 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0070_auto_20200125_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='slug',
            field=models.SlugField(),
        ),
    ]
