# Generated by Django 2.2.6 on 2020-01-28 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0073_auto_20200128_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctornotification',
            name='notif_status',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
