# Generated by Django 2.2.6 on 2020-02-01 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0074_doctornotification_notif_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doc_image',
            field=models.ImageField(blank=True, upload_to='profile_pictures/media'),
        ),
    ]
